// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkIpHrZ4F9Ibf-fFqxIiLJaZiLujyKomg',
    appId: '1:563825688140:android:22771626bc72bbcd187ee9',
    messagingSenderId: '563825688140',
    projectId: 'oshirasekun-4e5f3',
    storageBucket: 'oshirasekun-4e5f3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGEjHe0XRrmbtYIoWhZd6b1u5EagdZEyc',
    appId: '1:563825688140:ios:28198ae674d8b2bc187ee9',
    messagingSenderId: '563825688140',
    projectId: 'oshirasekun-4e5f3',
    storageBucket: 'oshirasekun-4e5f3.firebasestorage.app',
    iosClientId: '563825688140-n2r2k0jlid442b606piffsppeu52vdak.apps.googleusercontent.com',
    iosBundleId: 'com.inform.oshirasekun',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCGEjHe0XRrmbtYIoWhZd6b1u5EagdZEyc',
    appId: '1:563825688140:ios:28198ae674d8b2bc187ee9',
    messagingSenderId: '563825688140',
    projectId: 'oshirasekun-4e5f3',
    storageBucket: 'oshirasekun-4e5f3.firebasestorage.app',
    iosClientId: '563825688140-n2r2k0jlid442b606piffsppeu52vdak.apps.googleusercontent.com',
    iosBundleId: 'com.inform.oshirasekun',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQITASlF1nRUT6yNTI6dxFHpV45IjivHI',
    appId: '1:563825688140:web:c3e1cb3689feddcc187ee9',
    messagingSenderId: '563825688140',
    projectId: 'oshirasekun-4e5f3',
    authDomain: 'oshirasekun-4e5f3.firebaseapp.com',
    storageBucket: 'oshirasekun-4e5f3.firebasestorage.app',
    measurementId: 'G-NM6FB1KEV5',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBQITASlF1nRUT6yNTI6dxFHpV45IjivHI',
    appId: '1:563825688140:web:0ae7ede72c5d4dac187ee9',
    messagingSenderId: '563825688140',
    projectId: 'oshirasekun-4e5f3',
    authDomain: 'oshirasekun-4e5f3.firebaseapp.com',
    storageBucket: 'oshirasekun-4e5f3.firebasestorage.app',
    measurementId: 'G-RMHBFXWT4E',
  );

}